I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 127, in script
    if cont == 1 and qte_setup < 4:
  File "game/script.rpy", line 127, in <module>
    if cont == 1 and qte_setup < 4:
NameError: name 'qte_setup' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 127, in script
    if cont == 1 and qte_setup < 4:
  File "C:\Users\Riallot\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Riallot\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Riallot\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 127, in <module>
    if cont == 1 and qte_setup < 4:
NameError: name 'qte_setup' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Workshop2_Test 1.0
Mon Feb  6 18:42:53 2023
